# Generated by Django 2.1.5 on 2019-06-24 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacationInProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_date', models.DateField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacationTimeRangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime(2019, 6, 24, 8, 30, 43, 349267, tzinfo=utc))),
                ('date_to', models.DateField(default=datetime.datetime(2019, 6, 24, 8, 30, 43, 349267, tzinfo=utc))),
            ],
        ),
    ]
