# Generated by Django 2.1.5 on 2019-06-26 09:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_date', models.DateField(default=datetime.datetime(2019, 6, 26, 9, 10, 24, 577709, tzinfo=utc))),
                ('user_name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VacationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VacationTimeRangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime(2019, 6, 26, 9, 10, 24, 576706, tzinfo=utc))),
                ('date_to', models.DateField(default=datetime.datetime(2019, 6, 26, 9, 10, 24, 576706, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='vacationdetails',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.VacationsList'),
        ),
        migrations.AlterUniqueTogether(
            name='vacationdetails',
            unique_together={('list', 'unique_id')},
        ),
    ]
