# Generated by Django 2.1.5 on 2019-06-24 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190624_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 8, 31, 46, 542740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 8, 31, 46, 542740, tzinfo=utc)),
        ),
    ]
