# Generated by Django 2.1.5 on 2019-06-27 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190626_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationslist',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationdetails',
            name='vacation_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 10, 4, 11, 125589, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 10, 4, 11, 124586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 10, 4, 11, 124586, tzinfo=utc)),
        ),
    ]
