# Generated by Django 2.1.5 on 2019-06-24 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190624_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationinproject',
            name='hours',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 11, 36, 38, 27821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 11, 36, 38, 27821, tzinfo=utc)),
        ),
    ]
