# Generated by Django 2.1.5 on 2019-06-27 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190627_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationslist',
            name='vacationtimerangemodel_ptr',
        ),
        migrations.AddField(
            model_name='vacationslist',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 12, 29, 28, 387781, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='vacationslist',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 12, 29, 28, 387781, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='vacationslist',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationdetails',
            name='vacation_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 12, 29, 28, 387781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 12, 29, 28, 387781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 12, 29, 28, 387781, tzinfo=utc)),
        ),
    ]
