# Generated by Django 2.1.5 on 2019-06-27 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190627_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationslist',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='vacationslist',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='vacationslist',
            name='id',
        ),
        migrations.AddField(
            model_name='vacationslist',
            name='vacationtimerangemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.VacationTimeRangeModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationdetails',
            name='vacation_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 13, 35, 24, 516523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationslist',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 13, 35, 24, 515520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 13, 35, 24, 515520, tzinfo=utc)),
        ),
    ]
