# Generated by Django 2.1.5 on 2019-06-24 12:40

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0005_auto_20190624_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationinproject',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationinproject',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 12, 40, 29, 903875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 12, 40, 29, 903875, tzinfo=utc)),
        ),
    ]
