# Generated by Django 2.1.5 on 2019-06-24 13:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0006_auto_20190624_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_date', models.DateField()),
                ('user_name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VacationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.VacationDetails', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacationinproject',
            name='owner',
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 13, 39, 5, 124416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 13, 39, 5, 124416, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='VacationInProject',
        ),
    ]
