# Generated by Django 2.1.5 on 2019-06-24 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190624_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationslist',
            name='vacation',
        ),
        migrations.AddField(
            model_name='vacationdetails',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.VacationsList', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 13, 59, 3, 122962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 13, 59, 3, 123964, tzinfo=utc)),
        ),
    ]
