# Generated by Django 2.1.5 on 2019-06-25 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20190624_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationdetails',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.VacationsList'),
        ),
        migrations.AlterField(
            model_name='vacationdetails',
            name='vacation_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 10, 2, 20, 331213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 10, 2, 20, 330211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacationtimerangemodel',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 10, 2, 20, 331213, tzinfo=utc)),
        ),
    ]
