# Generated by Django 2.1.5 on 2019-06-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
