# Generated by Django 2.1.5 on 2019-06-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='test',
            new_name='test2',
        ),
    ]
