# Generated by Django 2.1.5 on 2019-08-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_nr', models.CharField(max_length=20)),
                ('lub_nr', models.CharField(max_length=20)),
                ('t1', models.DateField()),
                ('from_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okbv.OkbvFile')),
            ],
        ),
    ]
