# Generated by Django 2.1.5 on 2019-08-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nachtragfromdb',
            unique_together={('bus', 'version', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='nachtragfromdbfromfile',
            unique_together={('bus', 'version', 'type')},
        ),
    ]
