# Generated by Django 2.1.5 on 2019-08-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0002_auto_20190814_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NachtragFromDbFromFile',
            new_name='NachtragFromFile',
        ),
    ]
