# Generated by Django 2.1.5 on 2019-08-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0003_auto_20190814_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='okbvfile',
            name='is_file_processing',
            field=models.BooleanField(default=False),
        ),
    ]
