# Generated by Django 2.1.5 on 2019-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0004_nachtrag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nachtrag',
            old_name='Bus',
            new_name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together={('from_file', 'lub_nr')},
        ),
    ]
