# Generated by Django 2.1.5 on 2019-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0005_auto_20190816_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okbvfile',
            name='name',
            field=models.CharField(default='2019-08-16 08:33', max_length=50),
        ),
    ]
