# Generated by Django 2.1.5 on 2019-08-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0005_auto_20190813_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nachtrag',
            unique_together={('bus', 'version', 'type')},
        ),
    ]
