# Generated by Django 2.2.2 on 2019-08-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0006_auto_20190816_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okbvfile',
            name='name',
            field=models.CharField(default='2019-08-27 08:16', max_length=50),
        ),
    ]
