# Generated by Django 2.1.5 on 2020-02-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0007_auto_20190827_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okbvfile',
            name='name',
            field=models.CharField(default='2020-02-07 08:04', max_length=50),
        ),
    ]
