# Generated by Django 2.1.5 on 2019-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0007_auto_20190827_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachtragfromdb',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nachtragfromfile',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='okbvfile',
            name='name',
            field=models.CharField(default='2019-08-30 06:49', max_length=50),
        ),
    ]
