# Generated by Django 2.1.5 on 2019-08-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0008_auto_20190830_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='okbvfile',
            name='errors_list',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='okbvfile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
