# Generated by Django 2.1.5 on 2019-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0009_auto_20190830_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okbvfile',
            name='errors_list',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
