# Generated by Django 2.1.5 on 2019-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okbv', '0010_auto_20190830_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='plan_period',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
