# Generated by Django 2.1.5 on 2020-02-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_nr', models.CharField(max_length=20, null=True)),
                ('lub_nr', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('fassung_date', models.DateField(null=True)),
            ],
        ),
    ]
