# Generated by Django 2.1.5 on 2020-02-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emcos_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facotry_name', models.CharField(max_length=30, unique=True)),
                ('factory_letter', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emcos_form.Facory'),
        ),
    ]
