# Generated by Django 2.1.5 on 2020-02-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emcos_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmcosTask',
            fields=[
                ('bus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emcos_form.Bus')),
            ],
            bases=('emcos_form.bus',),
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50, unique=True)),
                ('task_type_text', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='emcostask',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emcos_form.TaskType'),
        ),
    ]
