# Generated by Django 2.1.5 on 2020-02-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emcos_form', '0002_auto_20200207_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='emcostask',
            name='additional_comments',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
