# Generated by Django 2.1.5 on 2020-02-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emcos_form', '0003_emcostask_additional_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emcostask',
            name='time_quantity',
            field=models.IntegerField(default=8),
        ),
    ]
